# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'scancentral -sscurl https://fortify.cw:8443/ssc -ssctoken 07f6ee7d-3d2c-4d0a-b875-36ca9c673cc0 start ‑upload -versionid 10013 -uptoken 07f6ee7d-3d2c-4d0a-b875-36ca9c673cc0 -b react_login_default -scan -v'
