# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 13.162

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: PowerShell@2
  inputs:
   targetType: 'inline'
   script: '[System.Environment]::SetEnvironmentVariable("NODE_EXTRA_CA_CERTS", "C:\selfsigned-w-san.cer", [System.EnvironmentVariableTarget]::Machine)'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://fortify.cw:8443/ssc/'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '10000'
    buildFailureCriteria: '[fortify priority order]:critical or [fortify priority order]:high'
    taskResultForBuildFailureCriteria: 'FAIL'
    buildTool: 'mvn'

